version: '3.8'

services:
  db:
    image: postgres:16
    container_name: inspection-db
    environment:
      POSTGRES_USER: belma
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: inspection
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:

